name: pylint

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: upgrade python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: uv add --dev pylint
      - name: Analysing the code with pylint
        run: |
          pylint py_sudoku_maker.__init__