name: sudoku_maker_tests

on:
  push:
    branches:
      - 'main'

jobs:
  tests-linter:
    runs-on: ubuntu-latest
    steps:
      # checks out repo and upgrades python version
      - uses: actions/checkout@v4
      - name: upgrade python
        uses: actions/setup-python@v5
      - name: install uv
        uses: astral-sh/setup-uv@v5
      - name: install deps
        run: uv add --dev pytest pylint
      - name: linter
        run: |
          uv run pylint py_sudoku_maker.__init__
      - name: unit tests
        run: |
          uv run pytest